# Generated by Django 5.2.5 on 2025-08-22 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_registration_amount_registration_card_last4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='stripe_payment_intent',
            new_name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='card_last4',
        ),
    ]
