# Generated by Django 5.2.5 on 2025-08-29 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('main', '0005_alter_hospital_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='cities_light.country'),
        ),
    ]
