# Generated by Django 5.2.5 on 2025-08-31 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_paymenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='created_at',
            new_name='paid_on',
        ),
    ]
