# Generated by Django 5.2.5 on 2025-08-31 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_created_at_paymenthistory_paid_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=50)),
                ('subscription_status', models.CharField(default='paid', max_length=50)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
