# Generated by Django 5.2.5 on 2025-08-22 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('stroke_risk', models.FloatField()),
                ('ct_result', models.CharField()),
                ('symptom_score', models.FloatField()),
                ('ct_image', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='nurse.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hypertension', models.BooleanField()),
                ('heart_disease', models.BooleanField()),
                ('ever_married', models.BooleanField()),
                ('stroke', models.BooleanField()),
                ('work_type', models.CharField(choices=[('children', 'children'), ('Govt_jov', 'Govt_jov'), ('Never_worked', 'Never_worked'), ('Private', 'Private'), ('Self-employed', 'Self-employed')], max_length=1024)),
                ('smoking_status', models.CharField(choices=[('formerly smoked', 'formerly smoked'), ('never smoked', 'never smoked'), ('smokes', 'smokes'), ('Unknown', 'Unknown')], max_length=1024)),
                ('bmi', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='doctor.patientrecord')),
            ],
        ),
    ]
