# Generated by Django 5.2.5 on 2025-08-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_patientrecord_ct_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='record',
            new_name='patient',
        ),
    ]
