# Generated by Django 5.2.5 on 2025-08-26 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_record_patientrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsymptom',
            name='Residence_type',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='patientsymptom',
            name='age',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsymptom',
            name='avg_glucose_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientsymptom',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='patientsymptom',
            name='work_type',
            field=models.CharField(choices=[('children', 'children'), ('Govt_job', 'Govt_job'), ('Never_worked', 'Never_worked'), ('Private', 'Private'), ('Self-employed', 'Self-employed')], max_length=1024),
        ),
    ]
