# Generated by Django 5.2.5 on 2025-08-30 11:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_patientsymptom_residence_type_patientsymptom_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='ct_image',
            field=models.ImageField(default='images/default.jpg', storage=django.core.files.storage.FileSystemStorage('D:\\Efaqah\\Efaqah\\doctor\\..\\private_ct_scans'), upload_to='ct'),
        ),
    ]
