# Generated by Django 5.2.5 on 2025-08-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_patientrecord_ct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='ct_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
