# Generated by Django 5.2.5 on 2025-08-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
