# Generated by Django 5.2.5 on 2025-08-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_patient_doctor_name'),
        ('nurse', '0002_patient_hospital'),
    ]

    operations = [
    ]
