# Generated by Django 5.2.5 on 2025-08-25 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_hospital_staffprofile'),
        ('nurse', '0003_merge_0002_patient_doctor_name_0002_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor_name',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staffprofile'),
        ),
    ]
