# Generated by Django 5.2.5 on 2025-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0004_alter_patient_doctor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_name',
            new_name='doctor',
        ),
    ]
